### ISSUE TITLE
Don't show unrelated nodes on mouseover

### ISSUE THREAD

**Issue by frewsxcv** [coyotebush/github-network-analysis#5]
if it's possible, when one mouses over a node A, it'd be nice if all the other titles of nodes not directly connected to A would disappear

**Comment by coyotebush** [comment]
Agreed that that would look nice.

I only figured out how to turn labels on because [this](https://github.com/jacomyal/sigma.js/commit/02cb7d076df72b34edaddc8b9c20bca5f874d27b) was the latest commit on plotter.js. Glancing at that logic, it doesn't support forcing labels off except through setting labelThreshold really high, but maybe I'll modify my fork to support forceLabel==-1.

**Comment by coyotebush** [comment]
sigma.js hackish fix in https://github.com/coyotebush/sigma.js/commit/3eea825c751d77c9e07e336ba426304341169f3a
